name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "production"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (PAT)
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$OWNER/finance-app-llmprocessor:${GITHUB_RUN_NUMBER} -f ./LLMProcessor.Dockerfile .

      - name: Push Docker image
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/$OWNER/finance-app-llmprocessor:${GITHUB_RUN_NUMBER}

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upgrade Azure Container Apps extension
        run: |
          az extension add --name containerapp --upgrade --yes

      - name: Update Azure Container App (LLM Processor)
        run: |
          set -x
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          az containerapp update \
            --name finance-app-llmprocessor \
            --resource-group projects \
            --image ghcr.io/$OWNER/finance-app-llmprocessor:${GITHUB_RUN_NUMBER} \
            --set-env-vars \
              LLM_API_KEY='${{ secrets.LLM_API_KEY }}' \
              RABBITMQ_HOST='${{ vars.RABBITMQ_HOST }}' \
              RABBITMQ_PORT='${{ vars.RABBITMQ_PORT }}' \
              RABBITMQ_VHOST='${{ vars.RABBITMQ_VHOST }}' \
              RABBITMQ_USER='${{ secrets.RABBITMQ_USER }}' \
              RABBITMQ_PASS='${{ secrets.RABBITMQ_PASS }}' \
              API_TOKEN='${{ secrets.API_TOKEN }}' \
